### PR TITLE
Agdigger 229

### PR DESCRIPTION
**Pull request by odra**
# Changes

Added expect module workflow if `jenkins_private_key_password` variable is defined

## How to test

Create a password protected private key (with the name id_rsa) and add a `jenkins_private_key_password` in `vars/buildfarm.yml` with the private key password.

### CODE REVIEW

**Comment by aliok** [comment]
@odra wow, I haven't realized that this change would make things a bit shittier when I was creating the task. I don't see any other way though :(

Just maybe one idea: have you ever seen something like a wrapper? I mean, perhaps we can do sth like following with a custom Ansible module:

```
- command_with_expect:
  command: java -jar /tmp/jenkins-cli.jar -remoting -s {{ jenkins_route_protocol | default('https') }}://{{ route_output.stdout }}  groovy /tmp/proxy-config.groovy
  responseQuestion: 'Enter passphrase for .*'
  response: "{{ jenkins_private_key_password }}"
  expectWhen: jenkins_private_key_password is defined
```

This could go "expect path" when `expectWhen==true`. Or, it could just execute the command otherwise.

I don't know if we can do something like this with a simple `include`. I haven't seen any example that include uses some kind of composition.

@odra @laurafitzgerald give me your thoughts on these ideas and then I can verify this if we keep it as is.

**Comment by odra** [comment]
yeah I don't like it as well (open to suggestions), I guess I could try to create a custom ansible module

**Comment by laurafitzgerald** [comment]
@aliok I couldn't find any documentation on a `command_with_expect` module. The logic in ansible is tricky and we've had to do something similar before using the `when` variable to decide on running particular tasks. @PhilipGough might have some insights on whether there is a better way to do this also?

**Comment by aliok** [comment]
@laurafitzgerald I was suggesting that we create a "command_with_expect" module ourselves. Sorry for not being clear.

yes, @PhilipGough any suggestions?

**Comment by PhilipGough** [comment]
@aliok @odra @laurafitzgerald Personally I don't like this for the gain we are getting an we are also forcing installation of another module/dependency onto their OpenShift master I believe? Correct me if I'm wrong. Not sure how desirable that would be to be honest as it seems a little invasive just so we can dismiss a requirement.

@odra I think I would look at seeing if you can do something with a custom module. We can then just create a `lib ` folder and drop it in there to use directly.

**Comment by aliok** [comment]
> @aliok @odra @laurafitzgerald Personally I don't like this for the gain we are getting an we are also forcing installation of another module/dependency onto their OpenShift master I believe? Correct me if I'm wrong. Not sure how desirable that would be to be honest as it seems a little invasive just so we can dismiss a requirement.

@PhilipGough sorry I think I didn't understand what you mean. 
You don't like the idea of having this improvement (that allows using a private key with a password)? or you don't like the custom module approach?

**Comment by odra** [comment]
I think the best route would be trying to extend the expect module to support the "expect when" parameter

**Comment by odra** [comment]
We would need an extra dependency anyway, either the "expect" system package or the "pexpect" python package

**Comment by aliok** [comment]
@PhilipGough yeah, as @odra said, we need to have the expect/pexpect on the machine if we want to do this. custom module or not. I was not able to find an alternative to Ansible's expect module unfortunately, when I was creating the JIRA.

**Comment by laurafitzgerald** [comment]
@aliok @odra in that case should we go with the solution provided in this pr? It's a bit tricky but I think that is down to the restrictions in the use of logic in ansible.

**Comment by PhilipGough** [comment]
@aliok sure ok. @laurafitzgerald yeah tend to agree now given the discussion. It is not as much benefit as I thought to do otherwise.

**Comment by aliok** [comment]
ok, we go as is then. let's verify this... 
👀 👀

**Comment by aliok** [comment]
ok, tested these scenarios:

* id_rsa HAS NO password; DIDN'T pass `jenkins_private_key_password`: all good, old behavior preserved
* id_rsa HAS NO password; passed `-e jenkins_private_key_password=password`: all good. (Ansible's `expect` module doesn't see that password is asked and everything goes smooth)
* id_rsa HAS a password; DIDN'T pass `jenkins_private_key_password`: failed as expected
* id_rsa HAS a password; passed WRONG `jenkins_private_key_password`: failed as expected
* id_rsa HAS a password; passed `jenkins_private_key_password`: all good

Merge it!

**Pull request merged**
