### PR TITLE
AGDIGGER-110 Reference kubeconfig file instead of elevating perms

### PR DESCRIPTION
**Pull request by aidenkeating**
Verification steps:
* Use @laurafitzgerald current PR on the RHMAP ansible installer that references the new aerogear.digger-installer.
* Execute in the base of that repo `ansible-galaxy install --force aerogear.digger-installer,AGDIGGER-110-reference-kubeconfig` to use this branch.
* Execute `ansible-playbook ....`.

@laurafitzgerald Would you mind taking a look? Not familiar with ansible at all so I could have missed something obvious.

### CODE REVIEW

**Comment by laurafitzgerald** [comment]
:eyes:

**Comment by laurafitzgerald** [comment]
Hi @aidenkeating. As per comment in [JIRA](https://issues.jboss.org/browse/AGDIGGER-110), we can keep the kubeconfig value in the defaults but don't require the value to be passed in the commands mentioned. Sorry for the confusion on this one.

**Comment by aidenkeating** [comment]
@laurafitzgerald No problem. Do we want `become: true` to be removed also, or does that need to be kept?

**Comment by laurafitzgerald** [comment]
@aidenkeating we can remove the become:true also as we don't need to be root run the `oc cp` command

**Comment by laurafitzgerald** [comment]
@aidenkeating looks good to merge

**Comment by aidenkeating** [comment]
@laurafitzgerald Removed the become: true statements based on [your comment above](https://github.com/aerogear/digger-installer/pull/1#issuecomment-309681123).  Would you mind taking one final look?

**Comment by laurafitzgerald** [comment]
@aidenkeating I've tested this locally and both commands run without `become:true` lgtm

**Pull request closed without merging**
