### PR TITLE
Add some additional tasks to fix irregular install bugs

### PR DESCRIPTION
**Pull request by PhilipGough**
ping @laurafitzgerald hit these when doing demo video

### CODE REVIEW

**Comment by laurafitzgerald** [comment]
@PhilipGough code changes lgtm, will verify this in the morning.

**Comment by PhilipGough** [comment]
@laurafitzgerald thanks, I'm also going to update the docs with this pr in regards to tag usage for the buildfarm work since it will probably be more useful here

**Comment by laurafitzgerald** [comment]
@PhilipGough 
**Case: additional plugins**
In this case the tasks completed successfully.
Is it correct that some of the plugins are skipped?
Is there a good way to verify this is correct?

**Case: polliing for android pod**
playbook paused to poll for the android pod to come up

**Case: added tags**
Tags looked fine. Tested `deploy_sdk_pod` and task were executed successfully
Only suggestion would be that the syntax we used before with tags is some-tag-name rather than some_tag_name. I'm not sure what the expected syntax is but I guess we should keep it consistent?

**Comment by laurafitzgerald** [comment]
also there was a failure in jenkins restarting (although I'm not sure if this is related to the changes made here)
```
fatal: [local.feedhenry.io]: FAILED! => {"changed": true, "cmd": ["java", "-jar", "/tmp/jenkins-cli.jar", "-remoting", "-s", "https://jenkins-digger.local.feedhenry.io", "restart"], "delta": "0:00:02.327443", "end": "2017-07-10 15:29:28.639197", "failed": true, "failed_when_result": true, "rc": 1, "start": "2017-07-10 15:29:26.311754", "stderr": "\nERROR: Unexpected exception occurred while performing restart command.\njava.lang.NullPointerException\n\tat jenkins.model.Jenkins.doRestart(Jenkins.java:4116)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:6........
```

**Comment by PhilipGough** [comment]
@laurafitzgerald 
 * It would be correct that they should be skipped if they are installed and the current version would meet the minimum required version
* Good, this is needed when the API might be slow and I saw a case where it went on to use the `deploy` pod which then goes away which is obviously a problem for the installer which has referenced this incorrect Pods name
* Okay, will look back at naming conventions and keep them the same

Docs updates to be included with this PR when I can get to it

**Comment by PhilipGough** [comment]
Closing in favour of https://github.com/aerogear/digger-installer/pull/29

**Pull request closed without merging**
