### PR TITLE
jenkins plugins and dependencies

### PR DESCRIPTION
**Pull request by odra**
#Jenkins Plugins

## Changes

Adds  android-signing dependencies plugin + xcode-plugin fork from aerogear

## Verification steps

```sh
ansible-playbook -i inventory.cfg digger-playbook.yml --tag=plugins
```

### CODE REVIEW

**Comment by odra** [comment]
I had some problems verifying it as I always get an authentication error from ansible playbook but running the jenkins-cli command myself works fine.

**Comment by aliok** [comment]
👁

**Comment by aliok** [comment]
@odra 

I created a fresh cluster to test this. Ran ansible-installer role and there were some errors:

```
WARNING: Some health checks are reporting as unhealthy: [plugins : There are 16 failed plugins: token-macro; config-file-provider; managed-scripts; github; github-branch-source; blueocean-pipeline-api-impl; blueocean-events; blueocean-dashboard; blueocean-git-pipeline; github-organization-folder; blueocean-github-pipeline; blueocean-personalization; blueocean-pipeline-editor; blueocean; android-signing; xcode-plugin]
```

Full log: https://gist.github.com/aliok/4bccc344e471844949cd7676e24e86a7

**Comment by odra** [comment]
closed due to #29

**Comment by aliok** [comment]
@odra ,  how is PR#29 is different than this PR? What was the problem?

**Comment by odra** [comment]
My pr was a duplicate of #29, problem was that we need to remove plugins first, restart jenkins, install plugins, restart again, etc - this work was already done in #29

**Pull request closed without merging**
